---
title: "NLP Assignment Coursera"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(ggplot2)
library(dplyr)
```

# Task 0

```{r cache=TRUE}
original_en_us_blogs <- read.delim("data/en_US/en_US.blogs.txt", skipNul=TRUE, header=FALSE, quote="")
original_en_us_news <- read.delim("data/en_US/en_US.news.txt", skipNul=TRUE, header=FALSE, quote="")
original_en_us_twitter <- read.delim("data/en_US/en_US.twitter.txt", skipNul=TRUE, header=FALSE, quote="")
```

# Task 1

```{r}
highest <- function(data)
{
  h <- 0
  for (val in data) {
    if(nchar(val)>h){
      h <- nchar(val)
    }
  }
  h
}
highest(original_en_us_blogs$V1)
highest(original_en_us_news$V1)
highest(original_en_us_twitter$V1)
```

```{r}
nrLove <- 0
nrHate <- 0

for (val in original_en_us_twitter$V1) {
  if (grepl("love", val)) {
    nrLove <- nrLove + 1
  }
  if (grepl("hate", val)) {
    nrHate <- nrHate + 1
  }
}
nrLove / nrHate
```

```{r}
for (val in original_en_us_twitter$V1) {
  if (grepl("biostats", val)) {
    print(val)
  }
}
```

```{r}
for (val in original_en_us_twitter$V1) {
  nrSentence <- 0
  if (grepl("^A computer once beat me at chess, but it was no match for me at kickboxing$", val)) {
    nrSentence <- nrSentence + 1
  }
}
nrSentence
```

# Task 2

```{r cache=TRUE}
words <- list()

evalBlogs <- sample(original_en_us_blogs$V1, 1000)
evalTweets <- sample(original_en_us_news$V1, 1000)
evalNews <- sample(original_en_us_twitter$V1, 1000)

evalText <- c(evalBlogs, evalTweets, evalNews)

for (line in evalText) {
  for (word in sapply(line, function(x) strsplit(line, split = " ")[[1]])) {
    if(exists(word, words)) {
      words[word] = words[[word]] + 1
    } else {
      words[word] = 1
    }
  }
}

countedWords <- as.data.frame(words) %>% gather()

sorted <- countedWords %>% arrange(desc(value))
sortedSubset <- sorted[1:50,]
ggplot(sortedSubset, aes(reorder(key, desc(value)), value)) + geom_col() + theme(axis.text.x = element_text(angle = 90, , hjust = 1))
```



```{r cache=TRUE}
pairs <- list()

evalBlogs2 <- sample(original_en_us_blogs$V1, 1000)
evalTweets2 <- sample(original_en_us_news$V1, 1000)
evalNews2 <- sample(original_en_us_twitter$V1, 1000)

evalText2 <- c(evalBlogs2, evalTweets2, evalNews2)

for (line in evalText2) {
  splitted <- sapply(line, function(x) strsplit(line, split = " ")[[1]])
  for (i in 2:length(splitted) - 1){
    word1 <- splitted[i]
    word2 <- splitted[i + 1]
    combination <- paste(word1, word2, sep = " ")
    
    if(exists(combination, pairs)) {
      pairs[combination] = pairs[[combination]] + 1
    } else {
      pairs[combination] = 1
    }
  }
}

countedWords2 <- as.data.frame(pairs) %>% gather()

sorted2 <- countedWords2 %>% arrange(desc(value))
sortedSubset2 <- sorted2[1:50,]
ggplot(sortedSubset2, aes(reorder(key, desc(value)), value)) + geom_col() + theme(axis.text.x = element_text(angle = 90, , hjust = 1))
```

```{r}
countedWords2 <- as.data.frame(pairs) %>% gather()

sorted2 <- countedWords2 %>% arrange(desc(value))
sortedSubset2 <- sorted2[1:50,]
ggplot(sortedSubset2, aes(reorder(key, desc(value)), value)) + geom_col() + theme(axis.text.x = element_text(angle = 90, , hjust = 1))
```











